# Generated by Django 3.2.9 on 2022-01-17 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='parent_id',
            field=models.PositiveBigIntegerField(null=True),
        ),
    ]
