# Generated by Django 3.2.9 on 2022-01-18 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0004_rename_user_comment_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='parent_id',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
    ]
