# Generated by Django 4.0.2 on 2022-02-07 07:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user_app', '0009_alter_comment_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='tour_site',
            new_name='tour_site_id',
        ),
        migrations.RenameField(
            model_name='rating',
            old_name='tour_site',
            new_name='tour_site_id',
        ),
        migrations.AlterField(
            model_name='comment',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_user_id', to=settings.AUTH_USER_MODEL),
        ),
    ]
