# Generated by Django 4.0.2 on 2022-02-10 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0010_rename_tour_site_comment_tour_site_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rating',
            old_name='username',
            new_name='user_id',
        ),
    ]
