# Generated by Django 4.0.2 on 2022-03-08 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0015_remove_profile_id_alter_profile_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='avatar_2x.png', upload_to=''),
        ),
    ]
