# Generated by Django 4.0.2 on 2022-04-20 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0021_alter_profile_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_avatar',
            field=models.ImageField(null=True, unique=True, upload_to=''),
        ),
    ]
