# Generated by Django 4.0.2 on 2022-04-20 13:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0022_profile_profile_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='comment_avatar',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='user_app.profile', to_field='profile_avatar'),
        ),
    ]
