# Generated by Django 4.0.2 on 2022-04-20 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0023_comment_comment_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='comment_profile',
        ),
    ]
