# Generated by Django 4.0.2 on 2022-04-20 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0025_alter_comment_comment_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='comment_avatar',
        ),
        migrations.AddField(
            model_name='comment',
            name='comment_avatar_url',
            field=models.URLField(null=True),
        ),
    ]
