# Generated by Django 4.0.2 on 2022-04-21 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0026_remove_comment_comment_avatar_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='avatar',
        ),
    ]
