# Generated by Django 4.0.2 on 2022-04-27 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0027_remove_profile_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment_avatar_url',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
