# Generated by Django 4.0.2 on 2022-05-02 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0028_alter_comment_comment_avatar_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_avatar',
            field=models.ImageField(null=True, unique=True, upload_to='avatars'),
        ),
    ]
