# Generated by Django 4.0.2 on 2022-05-10 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0029_alter_profile_profile_avatar'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-created_at'], 'verbose_name': 'comment', 'verbose_name_plural': 'comments'},
        ),
    ]
