# Generated by Django 4.0.2 on 2022-06-13 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0030_alter_comment_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment_avatar_url',
            field=models.URLField(max_length=2000, null=True),
        ),
    ]
