# Generated by Django 3.2.9 on 2021-11-10 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('slug', models.SlugField(help_text='A unique prepopulated field for object url', unique=True)),
                ('region', models.CharField(choices=[('A', 'AFRICA'), ('U', 'UNITED STATES'), ('P', 'ASIAN-PACIFIC'), ('E', 'EUROPE'), ('M', 'MIDDLE EAST')], max_length=100)),
                ('country', models.CharField(choices=[('EG', 'EGYPT'), ('MOR', 'MOROCCO'), ('S', 'SOUTH AFRICA'), ('T', 'TUNISIA'), ('A', 'ALGERIA'), ('Z', 'ZIMBABWE'), ('MO', 'MOZAMBIQUE'), ('IV', 'IVORY COST'), ('KE', 'KENYA'), ('BO', 'BOTSWANA'), ('US', 'USA'), ('ME', 'MEXICO'), ('CA', 'CANADA'), ('ARG', 'ARGENTINA'), ('DR', 'DOMINICAN REPUBLIC'), ('BR', 'BRAILLE'), ('Ch', 'CHILE'), ('PR', 'PERU'), ('CB', 'CUBA'), ('CL', 'COLOMBIA'), ('CH', 'CHAIN'), ('TH', 'THAILAND'), ('JP', 'JAPAN'), ('MS', 'MALAYSIA'), ('HK', 'HONG KONG'), ('MU', 'MACAU'), ('VT', 'VIETNAM'), ('SK', 'SOUTH KOREA'), ('IN', 'INDONESIA'), ('FR', 'FRANCE'), ('SP', 'SPAIN'), ('IT', 'ITALY'), ('TU', 'TURKEY'), ('GE', 'GERMANY'), ('UK', 'UNITED_KINGDOM'), ('AST', 'AUSTRALIA'), ('GRE', 'GREECE'), ('POR', 'PORTUGOL'), ('RU', 'RUSSIA'), ('UAE', 'UNITED ARAB EMIRATES'), ('SAU', 'SAUDI ARABIA'), ('LBN', 'LEBANON'), ('IS', 'ISRAEL'), ('JD', 'JORDAN'), ('Qt', 'QATAR'), ('IR', 'IRAN'), ('BHR', 'BAHRAIN'), ('IQ', 'IRAQ')], max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('tourist_traffic_annually', models.CharField(choices=[('V', 'VERY HIGH'), ('H', 'HIGH'), ('A', 'AVERAGE'), ('L', 'LAW')], default=False, max_length=1)),
                ('image', models.ImageField(blank=True, default='default.png', upload_to='media/')),
                ('short_description', models.CharField(blank=True, max_length=200)),
                ('long_description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_popular', models.BooleanField(default=False)),
                ('rating', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'tour_sites',
            },
        ),
    ]
