# Generated by Django 3.2.9 on 2021-11-15 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'category', 'verbose_name_plural': 'categories'},
        ),
        migrations.AlterModelOptions(
            name='tour',
            options={'verbose_name': 'tour', 'verbose_name_plural': 'tours'},
        ),
        migrations.AddField(
            model_name='tour',
            name='category',
            field=models.ManyToManyField(to='tour_app.Category'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='tourist_traffic_annually',
            field=models.CharField(blank=True, choices=[('V', 'VERY HIGH'), ('H', 'HIGH'), ('A', 'AVERAGE'), ('L', 'LAW')], default=False, max_length=1),
        ),
        migrations.AlterModelTable(
            name='category',
            table='tours_categories',
        ),
    ]
