# Generated by Django 3.2.9 on 2021-12-04 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour_app', '0002_auto_20211115_2010'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='dispaly_image_01',
            field=models.ImageField(blank=True, default='default.png', upload_to='media/'),
        ),
        migrations.AddField(
            model_name='tour',
            name='dispaly_image_02',
            field=models.ImageField(blank=True, default='default.png', upload_to='media/'),
        ),
        migrations.AddField(
            model_name='tour',
            name='dispaly_image_03',
            field=models.ImageField(blank=True, default='default.png', upload_to='media/'),
        ),
        migrations.AddField(
            model_name='tour',
            name='dispaly_image_04',
            field=models.ImageField(blank=True, default='default.png', upload_to='media/'),
        ),
    ]
