# Generated by Django 3.2.9 on 2021-12-08 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tour_app', '0004_auto_20211207_1840'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tour',
            options={'verbose_name': 'tour', 'verbose_name_plural': 'tours'},
        ),
    ]
