# Generated by Django 3.2.9 on 2021-12-08 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tour_app', '0005_alter_tour_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['-name'], 'verbose_name': 'category', 'verbose_name_plural': 'categories'},
        ),
    ]
