# Generated by Django 3.2.9 on 2021-12-09 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour_app', '0007_auto_20211208_0807'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='image',
            field=models.ImageField(blank=True, default='default.png', upload_to='static/media'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='image_01',
            field=models.ImageField(blank=True, default='default.png', upload_to='static/media'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='image_02',
            field=models.ImageField(blank=True, default='default.png', upload_to='static/media'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='image_03',
            field=models.ImageField(blank=True, default='default.png', upload_to='static/media'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='image_04',
            field=models.ImageField(blank=True, default='default.png', upload_to='static/media'),
        ),
    ]
