# Generated by Django 3.2.9 on 2021-12-22 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour_app', '0012_tour_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='price',
            field=models.IntegerField(),
        ),
    ]
