# Generated by Django 3.2.9 on 2022-01-02 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour_app', '0013_alter_tour_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tour',
            options={'default_manager_name': 'objects', 'ordering': ['name'], 'verbose_name': 'tour', 'verbose_name_plural': 'tours'},
        ),
        migrations.AlterField(
            model_name='tour',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
