# Generated by Django 3.2.9 on 2022-01-15 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tour_app', '0014_auto_20220102_2016'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tour',
            name='rating',
        ),
    ]
