# Generated by Django 4.0.2 on 2022-02-11 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour_app', '0015_remove_tour_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='numb_stars',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
