# Generated by Django 4.0.2 on 2022-02-11 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour_app', '0016_tour_numb_stars'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='numb_stars',
            field=models.PositiveSmallIntegerField(default=0, help_text='Value must not be grater than 5'),
        ),
    ]
