# Generated by Django 4.0.2 on 2022-03-27 22:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tour_app', '0018_tour_product_01_tour_product_01_afiliate_link_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tour',
            old_name='product_01_afiliate_link',
            new_name='product_01_affiliate_link',
        ),
        migrations.RenameField(
            model_name='tour',
            old_name='product_02_afiliate_link',
            new_name='product_02_affiliate_link',
        ),
        migrations.RenameField(
            model_name='tour',
            old_name='product_03_afiliate_link',
            new_name='product_03_affiliate_link',
        ),
        migrations.RenameField(
            model_name='tour',
            old_name='product_04_afiliate_link',
            new_name='product_04_affiliate_link',
        ),
        migrations.RenameField(
            model_name='tour',
            old_name='product_05_afiliate_link',
            new_name='product_05_affiliate_link',
        ),
        migrations.RenameField(
            model_name='tour',
            old_name='product_06_afiliate_link',
            new_name='product_06_affiliate_link',
        ),
        migrations.RenameField(
            model_name='tour',
            old_name='product_07_afiliate_link',
            new_name='product_07_affiliate_link',
        ),
    ]
