# Generated by Django 4.0.2 on 2022-04-08 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour_app', '0019_rename_product_01_afiliate_link_tour_product_01_affiliate_link_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='image',
            field=models.ImageField(blank=True, default='default.png', upload_to='destinations'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='image_01',
            field=models.ImageField(blank=True, default='default.png', upload_to='destinations'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='image_02',
            field=models.ImageField(blank=True, default='default.png', upload_to='destinations'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='image_03',
            field=models.ImageField(blank=True, default='default.png', upload_to='destinations'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='image_04',
            field=models.ImageField(blank=True, default='default.png', upload_to='destinations'),
        ),
    ]
