# Generated by Django 4.0.2 on 2022-04-08 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour_app', '0020_alter_tour_image_alter_tour_image_01_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='image',
            field=models.ImageField(blank=True, default='destinations/default.png', upload_to='destinations'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='image_01',
            field=models.ImageField(blank=True, default='destinations/default.png', upload_to='destinations'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='image_02',
            field=models.ImageField(blank=True, default='destinations/default.png', upload_to='destinations'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='image_03',
            field=models.ImageField(blank=True, default='destinations/default.png', upload_to='destinations'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='image_04',
            field=models.ImageField(blank=True, default='destinations/default.png', upload_to='destinations'),
        ),
    ]
