# Generated by Django 4.0.2 on 2022-07-07 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour_app', '0026_alter_tour_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='region',
            field=models.CharField(choices=[('AFRICA', 'AFRICA'), ('EUROPE', 'EUROPE'), ('NORTH AMERICA', 'NORTH AMERICA'), ('SOUTH AMERICA', 'SOUTH AMERICA'), ('ANTARCTICA', 'ANTARCTICA'), ('AUSTRAILA', 'AUSTRAILA'), ('ASIAN-PACIFIC', 'ASIAN-PACIFIC')], max_length=100),
        ),
    ]
