# Generated by Django 4.0.2 on 2022-03-01 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback_app', '0003_contactus_created_at_suggestion_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suggestion',
            name='message',
            field=models.TextField(),
        ),
    ]
